### ISSUE TITLE
Can turn off OPT code

### ISSUE THREAD

**Issue by rickywu** [soulteary/docker-sso-server#10]
I want to use outline offline deploy, so want to turn off OTP code, 
or can it support other OAUTH integration?

**Comment by soulteary** [comment]
Under the premise of limited authentication methods, turning off OTP is not conducive to facility safety.

But you can consider adding a mode similar to the demo to disable OTP.

**Comment by sukai-cheng** [comment]
@soulteary hello, developer, i didn't know how to set OTP code, when i login , it will appear ask me to input OTP code, but i didn't set OTP code any more, that really confused me
![屏幕录制2022-11-10 09 31 27](https://user-images.githubusercontent.com/35868545/200978636-edc755c1-18dc-4ac9-bdf8-a0b86c66c674.gif)

**Comment by soulteary** [comment]
I presume that on boot you skipped the interface to set the OTP, try reinitializing?

Or consider using a new version (opening soon) @sukai-cheng
